baseURL = "https://chanie0.github.io/"
languageCode = "en-us"
title = "chanie's Blog"
theme = "PaperMod"

[params]
  author = "chanie"
  showReadingTime = true
  defaultTheme = "auto"
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1